# Generated by Django 4.2.13 on 2024-07-04 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.DateField()),
                ('content_1M', models.TextField(blank=True, null=True)),
                ('content_1W', models.TextField(blank=True, null=True)),
                ('content_1D', models.TextField(blank=True, null=True)),
                ('content_4H', models.TextField(blank=True, null=True)),
                ('content_1H', models.TextField(blank=True, null=True)),
                ('content_15m', models.TextField(blank=True, null=True)),
                ('img_1M', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('img_1W', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('img_1D', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('img_4H', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('img_1H', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('img_15m', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('transaction_content', models.TextField(blank=True, null=True)),
                ('tp', models.TextField(blank=True, null=True)),
                ('sl', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
