# Generated by Django 4.2.13 on 2024-06-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economiccalendar',
            name='contents',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='economiccalendar',
            name='scheduled_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
