# Generated by Django 4.2.13 on 2024-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_economiccalendar_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField()),
                ('link', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
