# Generated by Django 4.2.13 on 2024-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economiccalendar',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
