# Generated by Django 4.2.13 on 2024-06-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_economiccalendar_scheduled_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='news_link',
        ),
        migrations.AddField(
            model_name='news',
            name='img_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
