# Generated by Django 4.2.11 on 2024-05-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_crypto_api_key_alter_crypto_api_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('open_time', models.DateTimeField()),
                ('open_timestamp', models.PositiveBigIntegerField()),
                ('close_time', models.DateTimeField()),
                ('close_timestamp', models.PositiveBigIntegerField()),
                ('side', models.CharField(max_length=10)),
                ('leverage', models.IntegerField(blank=True, null=True)),
                ('open_amount', models.FloatField()),
                ('close_amount', models.FloatField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('open_cost', models.FloatField()),
                ('close_cost', models.FloatField()),
                ('tp', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('open_commission_fee', models.FloatField()),
                ('close_commission_fee', models.FloatField()),
                ('funding_fee', models.FloatField()),
                ('insurance_clear', models.FloatField()),
                ('realized_pnl', models.FloatField()),
                ('pnl', models.FloatField()),
                ('pnl_percentage', models.FloatField()),
                ('open_balance', models.FloatField()),
                ('close_balance', models.FloatField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.crypto')),
            ],
        ),
    ]
