# Generated by Django 4.2.11 on 2024-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_tradehistory_leverage_alter_tradehistory_sl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='close_timestamp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='open_timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
