# Generated by Django 4.2.11 on 2024-05-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_alter_tradehistory_close_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeHistory',
        ),
    ]
